# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  airflow-latest = {
    pname = "airflow-latest";
    version = "64bb59216aeef7d7d66c425e2e68ddd02906dc14";
    src = fetchFromGitHub ({
      owner = "apache";
      repo = "airflow";
      rev = "64bb59216aeef7d7d66c425e2e68ddd02906dc14";
      fetchSubmodules = false;
      sha256 = "sha256-WaUomdCAmMy7zDfNZDazeOub/dho/G2eKyqUb/kw79I=";
    });
  };
  airflow-release = {
    pname = "airflow-release";
    version = "2.2.2";
    src = fetchFromGitHub ({
      owner = "apache";
      repo = "airflow";
      rev = "2.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-RTiDzCITl7qQQVGbKCCh3Esy4cPoejjsciGTiNECItA=";
    });
  };
  apache-airflow-providers-cncf-kubernetes = {
    pname = "apache-airflow-providers-cncf-kubernetes";
    version = "2.2.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-cncf-kubernetes/apache-airflow-providers-cncf-kubernetes-2.2.0.tar.gz";
      sha256 = "sha256-p0WvCQgVyn0Ww4eKrMER6NttQPs8z3uQN84aZKyuqxI=";
    };
  };
  apache-airflow-providers-ftp = {
    pname = "apache-airflow-providers-ftp";
    version = "2.0.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-ftp/apache-airflow-providers-ftp-2.0.1.tar.gz";
      sha256 = "sha256-xPWy+mG64/QoG8wLjCwp7agaIQegCq/VB4Hzlf6t0VY=";
    };
  };
  apache-airflow-providers-http = {
    pname = "apache-airflow-providers-http";
    version = "2.0.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-http/apache-airflow-providers-http-2.0.1.tar.gz";
      sha256 = "sha256-rf4jlHHZHvF1dvlLE8t3A1BOzJ86HTuePIlxwg1cZwE=";
    };
  };
  apache-airflow-providers-imap = {
    pname = "apache-airflow-providers-imap";
    version = "2.0.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-imap/apache-airflow-providers-imap-2.0.1.tar.gz";
      sha256 = "sha256-Yu9qSl4UyyH8SidTrwJPLa39Jf6V3cOTk189/mpTGy8=";
    };
  };
  apache-airflow-providers-sqlite = {
    pname = "apache-airflow-providers-sqlite";
    version = "2.0.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-sqlite/apache-airflow-providers-sqlite-2.0.1.tar.gz";
      sha256 = "sha256-mpkeEPi3vEAo/zs4nygGB+BkI/l9QyexNjg+alLZ/Pk=";
    };
  };
}
