# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  airflow-latest = {
    pname = "airflow-latest";
    version = "388f4e8b032fe71ccc9a16d84d7c2064c80575b3";
    src = fetchFromGitHub ({
      owner = "apache";
      repo = "airflow";
      rev = "388f4e8b032fe71ccc9a16d84d7c2064c80575b3";
      fetchSubmodules = false;
      sha256 = "sha256-tH4dHE4OjVMH0e33PSHPBxupoUr1lu5B+tjKfHFojvA=";
    });
  };
  airflow-release = {
    pname = "airflow-release";
    version = "2.2.4";
    src = fetchFromGitHub ({
      owner = "apache";
      repo = "airflow";
      rev = "2.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-JCcEgCq1sB8lBaeJy7QQbWU00sGAh5vUmJAptF8M9qo=";
    });
  };
  apache-airflow-providers-cncf-kubernetes = {
    pname = "apache-airflow-providers-cncf-kubernetes";
    version = "3.0.2";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-cncf-kubernetes/apache-airflow-providers-cncf-kubernetes-3.0.2.tar.gz";
      sha256 = "sha256-CeoQlq9+1d1JdbC+vxthLyTLnZ/pzQcNLzP7sbcBQ7k=";
    };
  };
  apache-airflow-providers-ftp = {
    pname = "apache-airflow-providers-ftp";
    version = "2.1.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-ftp/apache-airflow-providers-ftp-2.1.1.tar.gz";
      sha256 = "sha256-GBBmChbthNP6cmcbF2RXLpWo9k3tPhFeiFbL0BDtDF0=";
    };
  };
  apache-airflow-providers-http = {
    pname = "apache-airflow-providers-http";
    version = "2.1.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-http/apache-airflow-providers-http-2.1.1.tar.gz";
      sha256 = "sha256-T4XkQcgx8Lhaz3aWCyQD4dZYOR4uXsgoENKofOI7gYk=";
    };
  };
  apache-airflow-providers-imap = {
    pname = "apache-airflow-providers-imap";
    version = "2.2.2";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-imap/apache-airflow-providers-imap-2.2.2.tar.gz";
      sha256 = "sha256-JAq0XmB8trF1UUekMnHwLY50iSY3B/BXiWJF0K0psiQ=";
    };
  };
  apache-airflow-providers-sqlite = {
    pname = "apache-airflow-providers-sqlite";
    version = "2.1.2";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-sqlite/apache-airflow-providers-sqlite-2.1.2.tar.gz";
      sha256 = "sha256-fUjHqFGh8DYA0eYyICJTZYH6KxMzz1HVMUEo5qPJZWw=";
    };
  };
}
