# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  enso = {
    pname = "enso";
    version = "f225a962ce8678e3d533d8727d54ae79197a9ef6";
    src = fetchFromGitHub ({
      owner = "enso-org";
      repo = "enso";
      rev = "f225a962ce8678e3d533d8727d54ae79197a9ef6";
      fetchSubmodules = false;
      sha256 = "sha256-zflGkNAxiFxZ7AJnREK6mVsXJBW5CIQ4iDWLEQ88WuQ=";
    });
    date = "2022-11-24";
  };
}
