# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  enso = {
    pname = "enso";
    version = "37af06b14d86d4b888fb30778067e0a025b91c9c";
    src = fetchFromGitHub ({
      owner = "enso-org";
      repo = "enso";
      rev = "37af06b14d86d4b888fb30778067e0a025b91c9c";
      fetchSubmodules = false;
      sha256 = "sha256-nH4F1MW1skjjBBvmie0kqthlXeMfFyJo0RcIaxtiG/M=";
    });
    date = "2022-12-23";
  };
  enso-appimage = {
    pname = "enso-appimage";
    version = "2022.6.1";
    src = fetchurl {
      url = "https://github.com/enso-org/enso/releases/download/2022.7.1-nightly.2022.12.24/enso-linux-2022.7.1-nightly.2022.12.24.AppImage";
      sha256 = "sha256-ezb/11hCuEsBtJ6pWlSBjfxXClIP5mS72wvsAnAgm0c=";
    };
  };
  enso-engine = {
    pname = "enso-engine";
    version = "2022.6.1";
    src = fetchurl {
      url = "https://github.com/enso-org/enso/releases/download/2022.7.1-nightly.2022.12.24/enso-engine-2022.7.1-nightly.2022.12.24-linux-amd64.tar.gz";
      sha256 = "sha256-K62hOESbMsZMd00LMKyDMf72+ZktkK/tiCSOQp+0Ik4=";
    };
  };
}
