# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  skypilot = {
    pname = "skypilot";
    version = "742c1dc82e62322d4e6d61c68b021b816f6110ad";
    src = fetchFromGitHub ({
      owner = "skypilot-org";
      repo = "skypilot";
      rev = "742c1dc82e62322d4e6d61c68b021b816f6110ad";
      fetchSubmodules = false;
      sha256 = "sha256-y84ieC5P0KUyh5XISaxW3G/2CWCIbVHfc+maUyTzOs4=";
    });
    date = "2022-12-10";
  };
}
