# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  prefect = {
    pname = "prefect";
    version = "2.7.10";
    src = fetchFromGitHub ({
      owner = "PrefectHQ";
      repo = "prefect";
      rev = "2.7.10";
      fetchSubmodules = false;
      sha256 = "sha256-Vdj5NhwbQRM1sj+UbZXePW+SonSrmc7VTyfvTd/ryfc=";
    });
  };
  prefect-aws = {
    pname = "prefect-aws";
    version = "6fe4c564dc865e3500e663a99b346fb515222d07";
    src = fetchFromGitHub ({
      owner = "PrefectHQ";
      repo = "prefect-aws";
      rev = "6fe4c564dc865e3500e663a99b346fb515222d07";
      fetchSubmodules = false;
      sha256 = "sha256-93i0HFhq3zWJYn6ksain+wt3XQKNc9caBmscc24NNf8=";
    });
    date = "2023-01-25";
  };
  prefect-jupyter = {
    pname = "prefect-jupyter";
    version = "cc28cc12d108803828e706b59fc18261f3aa6f8c";
    src = fetchFromGitHub ({
      owner = "PrefectHQ";
      repo = "prefect-jupyter";
      rev = "cc28cc12d108803828e706b59fc18261f3aa6f8c";
      fetchSubmodules = false;
      sha256 = "sha256-L32+Ekwyy47nOE50teMcOFnM/yWtrJmyt58j1e4jAIE=";
    });
    date = "2023-01-09";
  };
  prefect-latest = {
    pname = "prefect-latest";
    version = "11828e9e09b2627ee4b66110712cda65d6a82922";
    src = fetchgit {
      url = "https://github.com/PrefectHQ/prefect";
      rev = "11828e9e09b2627ee4b66110712cda65d6a82922";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/zQ3fEnrxAgTKoumAT5FC0r0JiUenUSiZbUs/wH700I=";
    };
    date = "2023-01-26";
  };
}
