# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  prefect = {
    pname = "prefect";
    version = "2.7.1";
    src = fetchFromGitHub ({
      owner = "PrefectHQ";
      repo = "prefect";
      rev = "2.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-ztEnfLEimshXBDrqgEUpy0JVVHC/7mYdLGTMy6seCCU=";
    });
  };
  prefect-aws = {
    pname = "prefect-aws";
    version = "cdd40bdacec5465050e3fc4f174f4301db294ebc";
    src = fetchFromGitHub ({
      owner = "PrefectHQ";
      repo = "prefect-aws";
      rev = "cdd40bdacec5465050e3fc4f174f4301db294ebc";
      fetchSubmodules = false;
      sha256 = "sha256-XSJa2EJgH98168n4RHbVE5mYupqDleRoIjiWo7fSik0=";
    });
    date = "2022-12-07";
  };
  prefect-jupyter = {
    pname = "prefect-jupyter";
    version = "6ad26628113225cc8055849e258f64fb59070a6a";
    src = fetchFromGitHub ({
      owner = "PrefectHQ";
      repo = "prefect-jupyter";
      rev = "6ad26628113225cc8055849e258f64fb59070a6a";
      fetchSubmodules = false;
      sha256 = "sha256-EoyGquOyfzDRbDij0QQy+SKW3hwMlPR9EDOir/dvwQc=";
    });
    date = "2022-12-08";
  };
  prefect-latest = {
    pname = "prefect-latest";
    version = "33f7de508f740d3afb6bb7ab218ec035c7d40542";
    src = fetchgit {
      url = "https://github.com/PrefectHQ/prefect";
      rev = "33f7de508f740d3afb6bb7ab218ec035c7d40542";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-tF9ZA9lvfUhRHFdGRNc6I6qh1FnxNuHhhVnDfkqqjcQ=";
    };
    date = "2022-12-08";
  };
}
