# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  prefect = {
    pname = "prefect";
    version = "2.7.4";
    src = fetchFromGitHub ({
      owner = "PrefectHQ";
      repo = "prefect";
      rev = "2.7.4";
      fetchSubmodules = false;
      sha256 = "sha256-jzG+A+oXrX35vNJePvDNIr+dKD+P1RKR5777IeT6dMQ=";
    });
  };
  prefect-aws = {
    pname = "prefect-aws";
    version = "cdd40bdacec5465050e3fc4f174f4301db294ebc";
    src = fetchFromGitHub ({
      owner = "PrefectHQ";
      repo = "prefect-aws";
      rev = "cdd40bdacec5465050e3fc4f174f4301db294ebc";
      fetchSubmodules = false;
      sha256 = "sha256-XSJa2EJgH98168n4RHbVE5mYupqDleRoIjiWo7fSik0=";
    });
    date = "2022-12-07";
  };
  prefect-jupyter = {
    pname = "prefect-jupyter";
    version = "6ad26628113225cc8055849e258f64fb59070a6a";
    src = fetchFromGitHub ({
      owner = "PrefectHQ";
      repo = "prefect-jupyter";
      rev = "6ad26628113225cc8055849e258f64fb59070a6a";
      fetchSubmodules = false;
      sha256 = "sha256-EoyGquOyfzDRbDij0QQy+SKW3hwMlPR9EDOir/dvwQc=";
    });
    date = "2022-12-08";
  };
  prefect-latest = {
    pname = "prefect-latest";
    version = "7f86749d76c075bbfd38afc01dd61f758b3cbc19";
    src = fetchgit {
      url = "https://github.com/PrefectHQ/prefect";
      rev = "7f86749d76c075bbfd38afc01dd61f758b3cbc19";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-+uLsgEQ0rcYACQcp45MnDaA6fUfB4g5q4BZdSZZZAC4=";
    };
    date = "2022-12-23";
  };
}
