# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  malloy-composer = {
    pname = "malloy-composer";
    version = "v0.0.1676069706";
    src = fetchFromGitHub ({
      owner = "malloydata";
      repo = "malloy-composer";
      rev = "v0.0.1676069706";
      fetchSubmodules = true;
      sha256 = "sha256-8vJj9hUsPl4pTQrYET/8smt5dNbNOqQWg6Jkmu83HN4=";
    });
  };
  malloy-composer-latest = {
    pname = "malloy-composer-latest";
    version = "2217a1c0eeed54b0212e903af88a69853b36c616";
    src = fetchgit {
      url = "https://github.com/malloydata/malloy-composer";
      rev = "2217a1c0eeed54b0212e903af88a69853b36c616";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-7njiHx3FBb7oANRbcBwdMif3MK/ymzuZnk772gL4F00=";
    };
    date = "2023-03-10";
  };
}
