# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  malloy-composer = {
    pname = "malloy-composer";
    version = "v0.0.1670541413";
    src = fetchFromGitHub ({
      owner = "malloydata";
      repo = "malloy-composer";
      rev = "v0.0.1670541413";
      fetchSubmodules = true;
      sha256 = "sha256-PC+oL/UiIl6SmHXXgXk7kJr1GBTWckkbn2CyddBRXQs=";
    });
  };
  malloy-composer-latest = {
    pname = "malloy-composer-latest";
    version = "575468c857ded623fbf5f8afb9d3d46edc56d810";
    src = fetchgit {
      url = "https://github.com/malloydata/malloy-composer";
      rev = "575468c857ded623fbf5f8afb9d3d46edc56d810";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D6D5oVtbrmH2TbZfzKUYSHKgadheYhSwou4tgIEefyI=";
    };
    date = "2022-12-09";
  };
}
