# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  airflow-latest = {
    pname = "airflow-latest";
    version = "409a4de858385c14d0ea4f32b8c4ad1fcfb9d130";
    src = fetchFromGitHub ({
      owner = "apache";
      repo = "airflow";
      rev = "409a4de858385c14d0ea4f32b8c4ad1fcfb9d130";
      fetchSubmodules = false;
      sha256 = "sha256-qtWnbGq+DSCv3CihwCH7CzVO7faO+eK1t7KfQfHuFv4=";
    });
    date = "2022-11-08";
  };
  apache-airflow-providers-cncf-kubernetes = {
    pname = "apache-airflow-providers-cncf-kubernetes";
    version = "3.0.2";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-cncf-kubernetes/apache-airflow-providers-cncf-kubernetes-3.0.2.tar.gz";
      sha256 = "sha256-CeoQlq9+1d1JdbC+vxthLyTLnZ/pzQcNLzP7sbcBQ7k=";
    };
  };
  apache-airflow-providers-common-sql = {
    pname = "apache-airflow-providers-common-sql";
    version = "1.2.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-common-sql/apache-airflow-providers-common-sql-1.2.0.tar.gz";
      sha256 = "sha256-UQzXMgFCSFFBlnJ+ZJ7Sxwlg88SnO2K0whoqWL2StEU=";
    };
  };
  apache-airflow-providers-ftp = {
    pname = "apache-airflow-providers-ftp";
    version = "3.1.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-ftp/apache-airflow-providers-ftp-3.1.0.tar.gz";
      sha256 = "sha256-a4uuT65HwDl05Gf8C4yv0MKUGNcQsrezLxwRpUOJIWg=";
    };
  };
  apache-airflow-providers-http = {
    pname = "apache-airflow-providers-http";
    version = "4.0.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-http/apache-airflow-providers-http-4.0.0.tar.gz";
      sha256 = "sha256-GSUy+2y6DjbJJtkDCnDIO3jl5+xNxrOlsEsugLwDQx8=";
    };
  };
  apache-airflow-providers-imap = {
    pname = "apache-airflow-providers-imap";
    version = "3.0.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-imap/apache-airflow-providers-imap-3.0.0.tar.gz";
      sha256 = "sha256-3rYx8rOmLnTtYK1n2mma2hu5RWyWRphCob49FGg0kss=";
    };
  };
  apache-airflow-providers-sqlite = {
    pname = "apache-airflow-providers-sqlite";
    version = "3.2.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/a/apache-airflow-providers-sqlite/apache-airflow-providers-sqlite-3.2.1.tar.gz";
      sha256 = "sha256-UVYIFzdSBueS0r8lS0uiOV/yQ5Mcc4w1ZY311Vy2j8c=";
    };
  };
  papermill = {
    pname = "papermill";
    version = "2.4.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/papermill/papermill-2.4.0.tar.gz";
      sha256 = "sha256-b4+KmwazlnfyB8CRAMjThrz1kvDLvdqfD1DoFEVpdic=";
    };
  };
}
